// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorials: [{ type: "autogenerated", dirName: "tutorials" }],
  contribute: [{ type: "autogenerated", dirName: "contribute" }],
  lab: [{ type: "autogenerated", dirName: "lab" }],
  learn: [{ type: "autogenerated", dirName: "learn" }],
}

module.exports = sidebars
