// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  cool: [{ type: "autogenerated", dirName: "cool" }],
  contribute: [{ type: "autogenerated", dirName: "contribute" }],
  lab: [{ type: "autogenerated", dirName: "lab-dev" }],
  learn: [{ type: "autogenerated", dirName: "learn" }],
  internships: [{ type: "autogenerated", dirName: "internships" }],
}

module.exports = sidebars
