// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorials: [{ type: "autogenerated", dirName: "tutorials" }],
  contributing: [{ type: "autogenerated", dirName: "contributing" }],
  lab: [{ type: "autogenerated", dirName: "lab" }],
}

module.exports = sidebars
